FROM node:20 AS builder

WORKDIR /app

COPY package*.json package-lock.json ./
COPY client/package*.json package-lock.json ./client/
COPY server/package*.json package-lock.json ./server/

RUN npm ci

COPY client ./
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
