# Use Node.js for building the app
FROM node:20 

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the app files
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]