# Use Node.js for building the app
FROM node:20 

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the application
RUN npm run build

EXPOSE 5000

# Run the server in development mode
CMD ["npm", "run", "dev"]