# Use Node.js for building the app
FROM node:20 

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm install

# Install TypeScript tools globally
RUN npm install -g typescript ts-node nodemon

EXPOSE 5000